### PR TITLE
feat: add example dropdown

### LINKED ISSUE #3: Add examples in a drown-down
So you don't have to copy paste them from flix.dev

### PR DESCRIPTION
**Pull request by sockmaster27**
Fixes #3

### CODE REVIEW

**Comment by sockmaster27** [comment]
Looks like this:
image

**Comment by sockmaster27** [comment]
This does contain a lot of duplication from flix.dev, but as it's structured right now, I don't see any way around that.

**Comment by magnus-madsen** [comment]
Conflicted.

**Comment by magnus-madsen** [comment]
I think its OK with the duplication. Maybe we can change the text to:

```
-- select example --
```

**Review by magnus-madsen — APPROVED** [review]

**Comment by magnus-madsen** [comment]
Now live at https://play.flix.dev/

**Pull request merged**
