### PR TITLE
ci: upgrade to Node v18

### LINKED ISSUE #11: Upgrade to Node.js 18

### LINKED ISSUE #12: Add/configure CI build
Not sure if this requires extra permissions, or can be done by just adding the right files?

We can probably see how flix.dev is configured.

### PR DESCRIPTION
**Pull request by sockmaster27**
Fixes #11, #12

### CODE REVIEW

**Comment by magnus-madsen** [comment]
This does not fix the CI. We need to add a .github folder with a workflow (?)

**Comment by sockmaster27** [comment]
@magnus-madsen 
The `.github` folder already seems to be identical to flix.dev's?

**Comment by sockmaster27** [comment]
I'm not sure I understand what you mean

**Comment by magnus-madsen** [comment]
Yes. My bad, must be tired.

**Comment by magnus-madsen** [comment]
Does this need react-scripts to be updated?

**Comment by sockmaster27** [comment]
@magnus-madsen 
Yes, build fails otherwise

**Pull request merged**
